<?php 
    if(!Mage::getSingleton('customer/session')->isLoggedIn()){
        echo "//not logged in";
        Mage::app()->getResponse()->setRedirect(Mage::getBaseUrl()); 
    }else
    {
        //echo "// logged in";
	?>
<?php    

$db = Mage::getSingleton('core/resource')->getConnection('core_write');
$tbl = $db->getTableName('MyModule');
$sql = "select * from `".$tbl."` ORDER BY id DESC  ";
$tickets = $db->fetchAll($sql);
//print_r($tickets);


?>
<table id="my-orders-table" class="data-table orders">
<colgroup><col width="1">
<col width="1">
<col>
<col width="1">
<col width="1">
<col width="1">
</colgroup><thead>
<tr class="first last">
<th class="number">#Ticket Id</th>
<th class="number">#Order Id</th>

<th class="ship">Message</th>
<th class="total"><span class="nobr">Request Type</span></th>
<th class="status"><span class="nobr">Ticket Status</span></th>
<th class="date">Date/time</th>
<th class="view">&nbsp;Action</th>
</tr>
</thead>
<tbody>
	<?
	foreach ($tickets as $ticket):
	

	?>
	
<tr class="first last odd">
<td class="number"><? echo $ticket['id']; ?></td>
<td class="number">#<? echo $ticket['orderid']; ?></td>

<td class="ship"><? echo $ticket['message']; ?></td>
<td class="total"><span class="price"></span><? echo $ticket['request_type']; ?></td>
<td class="status"><em><? echo $ticket['status']; ?></em></td>
<td class="date"><span class="nobr"><? echo $ticket['c_time']; ?></span></td>
<td class="a-center view last">
<span class="nobr"><a href="<?php echo $this->getUrl('mymodule/index/reply');?>?tktid=<? echo $ticket['orderid']; ?>">View </a>

</span>
</td>
</tr>
<?

endforeach;

?>

</tbody>
</table>
        
<?
    }
    
    //~ while($row = $db->fetchRow($sql)){
	//~ echo "dd";
//~ 
	//~ } 
//~ while ($row = $sqlQuery->fetch() ) {
	//~ print_r($row);
//~ }
    //~ $resource = Mage::getSingleton('core/resource');
    //~ $customer = Mage::getSingleton('customer/session')->getCustomer();
	//~ $read = $resource->getConnection('core_read');
	//~ 
	//~ $tbl = $resource->getTableName('MyModule');
    //~ $sql = "Select * from '".$tbl."' ";
    //~ $sqlQuery = $resource->query($sql);
    //~ while ($row = $sqlQuery->fetch() ) {
            //~ echo $row['id'];
    //~ }
//~ 
    //$rows = $read->fetchAll($sql); //fetchRow($sql), fetchOne($sql),...
    //Zend_Debug::dump($rows);
 //~ 

?>
