<h3>MyModulereply </h3>
<?php    

$db = Mage::getSingleton('core/resource')->getConnection('core_write');
$tbl = $db->getTableName('MyModule');
$sql = "select * from `".$tbl."` where `id` = '".$_REQUEST['t_id']."' ";
$tickets = $db->fetchAll($sql);
//print_r($tickets);
  $currentUrl = $this->helper('core/url')->getCurrentUrl();
?>


<form action="<?php echo $currentUrl; ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>

        <input type="hidden" name="CUrl" value="<?php echo $currentUrl;?>" / >

<table id="my-orders-table" class="data-table orders">
<colgroup><col width="1">
<col width="1">
<col>
<col width="1">
<col width="1">
<col width="1">
</colgroup><thead>
<tr class="first last">
<th class="number">#Ticket Id</th> 
<th class="number">#Order Id</th>
<th class="ship">Message</th>
<th class="total"><span class="nobr">Request Type</span></th>
<th class="status"><span class="nobr">Ticket Status</span></th>
<th class="date">Date/time</th>
<th class="view">&nbsp;###</th>
<th class="view">&nbsp;###</th>
</tr>
</thead>
<tbody>
<?
	foreach ($tickets as $ticket):
?>
<tr class="first last odd">
<td class="number"><? echo $ticket['id']; ?></td>
<td class="number">#<? echo $ticket['orderid']; ?></td>
<td class="ship"><? echo $ticket['message']; ?></td>
<td class="total"><span class="price"></span><? echo $ticket['request_type']; ?></td>
<td class="status"><em><? if($ticket['status']=="Pending"){ echo "<font color='orange'>".$ticket['status']."<font>"; } else{
echo "<font color='green'>".$ticket['status']."<font>";
} ?></em></td>
<td class="date"><span class="nobr"><? echo $ticket['c_time']; ?></span></td>
<td class="a-center view last">
<?
	if($ticket['status']=="Pending")
	{ 
		?>
	<?php if($ticket['ReplyMsg']==""){ ?>
	<textarea name="ReplyMsg"><?php echo $ticket['ReplyMsg']; ?></textarea>
	<span class="nobr">
	<input type="submit" name="submit" value="Send">
	</span>
	<? 
	} 
	}
	else
	{
	
	echo $ticket['ReplyMsg'];
	}
	?>

</td>
<td>
&nbsp; <a class="" href="<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/sales_order/view", array('order_id'=>'3')); ?>"><span>View Order</span></a>
</td>
</tr>

       

<?php

?>
<?php
//Mage::app()->getResponse()->setRedirect(Mage::getBaseUrl().'mymodule/adminhtml_mymodulebackend/index'); 
if(isset($_REQUEST['CUrl'])){
	}

?>
<?
endforeach;
?>
</tbody>
</table>
</form>
